package infrastructure.ui.tourist;

import api.Controller;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import models.entity.Tourist;

import javax.swing.*;

import java.awt.*;

import static api.Main.SCREEN_HEIGHT;
import static api.Main.SCREEN_WIDTH;

public class Profile extends JFrame {
    private JButton редактироватьButton;
    private JPanel totalPanel;
    private JPanel changingPanel;
    private JLabel lName;
    private JLabel lAge;
    private JLabel lPassport;
    private JRadioButton мRadioButton;
    private JRadioButton жRadioButton;
    private JPanel changeSex;
    private JLabel lSex = new JLabel();
    private JTextField nameField = new JTextField();
    private JTextField ageField = new JTextField();
    private JTextField passportField = new JTextField();

    public Profile(Controller controller, Long id) {
        Tourist tourist = controller.getTouristById(id);
        String name = tourist.getName();
        if (name.length() > 20) {
            String[] fio = name.split(" ");
            name = "<html>" + fio[0] + "<br>" + fio[1] + "<br>" + fio[2];
        }
        lName.setText(name);
        lAge.setText(String.valueOf(tourist.getAge()));
        lPassport.setText(tourist.getPassport());
        lSex.setText(tourist.getSex());
        changingPanel.remove(changeSex);
        changingPanel.setLayout(new GridLayout(4, 1));
        changingPanel.add(lSex);
        setTitle("Profile");
        setLocation(
                (SCREEN_WIDTH - totalPanel.getPreferredSize().width) / 2,
                (SCREEN_HEIGHT - totalPanel.getPreferredSize().height) / 2
        );
        setContentPane(totalPanel);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);


        редактироватьButton.addActionListener(e -> {
            if (редактироватьButton.getText().equals("Редактировать")) {
                final Tourist updatedTourist = controller.getTouristById(id);
                changingPanel.remove(lName);
                changingPanel.remove(lAge);
                changingPanel.remove(lPassport);
                changingPanel.remove(lSex);
                changingPanel.setLayout(new GridLayout(4, 1));
                nameField.setText(updatedTourist.getName());
                ageField.setText(String.valueOf(updatedTourist.getAge()));
                passportField.setText(updatedTourist.getPassport());
                changingPanel.add(nameField);
                changingPanel.add(ageField);
                changingPanel.add(passportField);
                мRadioButton.setSelected(false);
                жRadioButton.setSelected(false);
                changingPanel.add(changeSex);
                редактироватьButton.setText("Сохранить");
                validate();
                repaint();
            }


            //if button 'save'
            else {
                String sex;
                if (мRadioButton.isSelected()) sex = "m";
                else if (жRadioButton.isSelected()) sex = "f";
                else {
                    JOptionPane.showMessageDialog(null, "Выберите пол");
                    return;
                }
                int r = controller.updateTourist(
                        id,
                        nameField.getText(),
                        Integer.parseInt(ageField.getText().trim()),
                        passportField.getText(),
                        sex
                );
                final Tourist updatedTourist = controller.getTouristById(id);
                if (r == -1) {
                    JOptionPane.showMessageDialog(null, "Неверно заполнены данные");
                    return;
                }
                changingPanel.remove(nameField);
                changingPanel.remove(ageField);
                changingPanel.remove(passportField);
                changingPanel.remove(changeSex);
                changingPanel.setLayout(new GridLayout(4, 1));

                String touristName = updatedTourist.getName();
                if (touristName.length() > 20) {
                    String[] fio = touristName.split(" ");
                    touristName = "<html>" + fio[0] + "<br>" + fio[1] + "<br>" + fio[2];
                }

                lName.setText(touristName);
                lAge.setText(String.valueOf(updatedTourist.getAge()));
                lPassport.setText(updatedTourist.getPassport());
                lSex.setText(updatedTourist.getSex());
                changingPanel.add(lName);
                changingPanel.add(lAge);
                changingPanel.add(lPassport);
                changingPanel.add(lSex);
                редактироватьButton.setText("Редактировать");
                validate();
                repaint();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        totalPanel = new JPanel();
        totalPanel.setLayout(new GridLayoutManager(8, 4, new Insets(0, 0, 0, 0), -1, -1));
        totalPanel.setMinimumSize(new Dimension(250, 202));
        totalPanel.setPreferredSize(new Dimension(250, 250));
        final JLabel label1 = new JLabel();
        label1.setText("ФИО");
        totalPanel.add(label1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        totalPanel.add(spacer1, new GridConstraints(5, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 5), null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Возраст");
        totalPanel.add(label2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Паспорт");
        totalPanel.add(label3, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Пол");
        totalPanel.add(label4, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        totalPanel.add(spacer2, new GridConstraints(0, 0, 8, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(20, -1), new Dimension(20, -1), null, 0, false));
        final Spacer spacer3 = new Spacer();
        totalPanel.add(spacer3, new GridConstraints(0, 3, 8, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(20, -1), new Dimension(20, -1), null, 0, false));
        final Spacer spacer4 = new Spacer();
        totalPanel.add(spacer4, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
        редактироватьButton = new JButton();
        редактироватьButton.setText("Редактировать");
        totalPanel.add(редактироватьButton, new GridConstraints(6, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        totalPanel.add(spacer5, new GridConstraints(7, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 10), new Dimension(-1, 10), null, 0, false));
        changingPanel = new JPanel();
        changingPanel.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        totalPanel.add(changingPanel, new GridConstraints(1, 2, 4, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lName = new JLabel();
        lName.setText("Label");
        changingPanel.add(lName, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lAge = new JLabel();
        lAge.setText("Label");
        changingPanel.add(lAge, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lPassport = new JLabel();
        lPassport.setText("Label");
        changingPanel.add(lPassport, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        changeSex = new JPanel();
        changeSex.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        changingPanel.add(changeSex, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        жRadioButton = new JRadioButton();
        жRadioButton.setText("ж");
        changeSex.add(жRadioButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        мRadioButton = new JRadioButton();
        мRadioButton.setText("м");
        changeSex.add(мRadioButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(жRadioButton);
        buttonGroup.add(мRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return totalPanel;
    }
}
